sudo: false

language: cpp

matrix:
  include:
    - os: linux
      env: CONDA_PY=3.5
    - os: linux
      env: CONDA_PY=3.6
    - os: osx
      env: CONDA_PY=3.5
    - os: osx
      env: CONDA_PY=3.6

install:
  # Set the anaconda environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$CONDA_PY" == "2.7" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh;
      else
        curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi;
    else
      if [[ "$CONDA_PY" == "2.7" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels defaults
  - conda update -q --all
  - conda install conda-build numpy anaconda-client
  # build
  - conda build -c $CONDA_CHANNEL --skip-existing conda-recipe

script:
  - echo "No test scripts to be run!"

deploy:
  provider: script
  script: find $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64 -name "*.tar.bz2" -exec anaconda -t $CONDA_TOKEN upload {} \;
